### ISSUE TITLE
Error for mat2npy

### ISSUE THREAD

**Issue by matsui528** [dangoron/diffusion#1]
`make mat2npy` causes the following error.
```
mat2npy.py: error: argument --dataset_name: invalid choice: 'oxford' (choose from 'oxford5k', 'oxford105k', 'paris6k', 'paris106k')
```

**Comment by fyang93** [comment]
Fixed in the newest commit

**Comment by matsui528** [comment]
still have some errors:
```
python mat2npy.py \
        --dataset_name oxford5k \
        --feature_type resnet \
        --mat_dir ./data
Traceback (most recent call last):
  File "mat2npy.py", line 50, in <module>
    with h5py.File(os.path.join(args.mat_dir, input_file), 'r') as f:
  File "/home/ubuntu/anaconda/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ubuntu/anaconda/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './data/oxford5k_resnet.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Makefile:23: recipe for target 'mat2npy' failed
make: *** [mat2npy] Error 1

```
